### ISSUE TITLE
baseUrl -- what's the intent?

### ISSUE THREAD

**Issue by laurelnaiad** [Vertafore/grunt-docular#4]
I'm a little confused about the baseUrl configuration option.  When I set it to "/stuff" here's what I see
- "localhost:port/", as might be expected, is broken, but in a "script didn't load" sort of way;
- "localhost:port/stuff" shows the main documentation page, as I would expect
- the "docular link" on all of the pages goes to localhost:port/, and that is broken as stated before
- other internal links go to localhost:port/documentation, thereby mostly breaking out of the baseUrl.

So I'm wondering if that' s how it's supposed to work, and what purpose it might serve.  Is it a work in progress?  I would have expected that it would be used to make the entire site run in localhost:port/stuff..., which, given that docular-server (an active server) is currently required, doesn't seem to be all of that appealing anyway....

**Comment by gitsome** [comment]
I too am a little confused on this one. It was ported over form the original AngularJS documentation.  I did have an error at one point and had to look at the angular source to determine why I was getting error and it was due to this baseURL setting. I believe your assumptions on how it should work are right on but I haven't followed up with this one yet.  I think this explains it somewhat http://stackoverflow.com/questions/14751836/is-it-possible-to-change-the-base-url-in-angular  It would be good to get a better handle on this and refine + document it.

**Comment by laurelnaiad** [comment]
See comment in the issue about url rewriting -- there are two baseUrl variables in index.html right now... both of which are acting funny --  then there's the whole issue of base href which some versions of angular are now requiring due to what I think is a recent bug in angular... http://stackoverflow.com/questions/16828988/angularjs-hashbang-url-keeps-appending-to-itself-on-full-refresh/16844466#16844466 .  Regardless of the base href situation, something has never seemed right with the whole issue of base urls in angular.
