### ISSUE TITLE
Crash with node > 0.10.5

### ISSUE THREAD

**Issue by ghost** [Vertafore/grunt-docular#7]
Docular is not able to create documentation with this version of nodejs.
I've got bunch of

```
(node) warning: Recursive process.nextTick detected. This will break in the next version of node. Please use setImmediate for recursive deferral.
```

and then

```
RangeError: Maximum call stack size exceeded
```

I've managed to work around this by replacing all "process.nextTick" -> "setImmediate" in docular source

```
Done, without errors. ;)
```

**Comment by gitsome** [comment]
Yikes! Big bug!  Thanks @d3vilroot. Taking a look.

**Comment by laurelnaiad** [comment]
For what it's worth, you might want to invest in https://github.com/visionmedia/n (or something similar) if you're going to hunt down node compatibility issues.  I haven't used it, but TJ obviously has a reliable track record.  I haven't experienced "node version h_ll" -- only purgatory, but I imagine the true h_ll is a very "special" place.

**Comment by gitsome** [comment]
LOL, yes, I dipped my toes in to node version h*ll briefly while looking into this issue and it was indeed scary.
I did a search for the nextTick usage within the dependencies and found that "QQ" used it. Since "QQ" is deprecated I pulled it out and just used regular "Q" and that fixed the problem (I think).. See #78.

I will look more into your link however moving forward so I don't have to worry about that "special" place. Thanks @stu-salsbury 

So @d3vilroot, I did a version bump on "docular" so take a look at #78 comments to uninstall and re-install grunt-docular to pull in the new version and let us know if it fixes your problem.

I noticed you already replaced all your nextTick's so maybe a non-issue for you.
