### ISSUE TITLE
(Questions) General help using grunt-docular

### ISSUE THREAD

**Issue by collinforrester** [Vertafore/grunt-docular#9]
First off, great work putting together what you've done so far.
1. Is there an easy way to extract the template that grunt-docular uses and point it to use a different directory?  Right now I've just been using the built in templates and when I want to add/remove css or js files I modify the templates inside of the node_modules directory.  This works great for me but as I want to use this on a few projects here at work it will not work because I don't want everyone to have to make these changes.
2. Somewhat related to my first question, is there a built in way to link built files in my current to the generated docs?  I have a set of directives that I'm generating this documentation for and right now I'm outputting 2 files.  One in my /dist directory and another in the /node_modules directory where the file server is ran.  Ideally I'd be able to include files from my root workspace.  It also appears the directives that I've written aren't being executed on my example code but I think its related to how I'm linking them on the page and I need to add my angular module to the code that is executed on the docs page.
3. Last question.  If either of the things I've asked above can be fixed by a code change then point me in the right direction and I'll try to help out.  Just thought I'd check first to see if there was a configuration change I could do.

Again, great project.  My project is a set of directives to help jQuery Mobile components work better with Angular.  So the complexity is a little higher since I need to load jQM on the page, then, these angular directives, then get them to run.

Thanks.

**Comment by gitsome** [comment]
Hey @collinforrester!

1). Yes, the latest version has a configuration in the Gruntfile.js file you can add called "docular_webapp_target". This will export the webapp to a directory of your choice relative to where your Gruntfile.js file resides. See documentation here: http://grunt-docular.com/documentation/docular/docularconfigure/docular-webapp-target

Note though, that everytime you run the docular grunt task that it will overwrite the entire directory. There is an issue logged to attempt to only overwrite unmodified files, the details are still being worked out. There are also configuration to supply your own js and css files as well as customized homepage templates that are added during the docular task so those will always persist.

Customizing home page template:
http://grunt-docular.com/documentation/docular/docularconfigure/partials

Adding CSS and JS:
You can add your own CSS and JS files as an array of paths to files you want to include. See the configuration used for grunt-docular.com

``` js
module.exports = function(grunt) {

    // Project configuration.
    grunt.initConfig({

        pkg: grunt.file.readJSON('package.json'),

        'docular': {

            showDocularDocs: true,
            showAngularDocs: true,
            docular_partial_home: 'home.html',
            docular_partial_navigation: 'navigation.html',
            docular_webapp_target: 'grunt-docular-webapp',
            javascript: [],
            css: ['resources/css/grunt_docular.css'],
            plugins: [
                {
                    id: 'docular-plugin-github',
                    configs: {
                        client: {
                            owner: 'gitsome',
                            repo: 'docular'
                        },
                        server: {
                            client_id: 'b586832d3e7bc1f6eaad',
                            client_secret: 'ebbb113343dba77e5f1feafd8e236c1b071196ff'
                        }
                    }
                }
            ],
            analytics: {
                account: 'UA-40646426-1',
                domainName: 'grunt-docular.com'
            },
            discussions: {
                shortName: 'johndavidfive',
                url: 'http://johndavidfive.com',
                dev: false
            },
            groups: []
        },

        'docular-server': {
            port: 8000
        }

    });

    // Load the plugin that provides the "docular" tasks.
    grunt.loadNpmTasks('grunt-docular');

    // Default task(s).
    grunt.registerTask('default', ['docular']);

};
```

**Comment by gitsome** [comment]
Okay, so github is acting funny I am having to split up my answers:

2) I myself have not tried to include angular modules so that examples run just as the native angularjs examples run. You would need to have those added to the list of js and css files to inject into the page. You are right, this would be done the same way as described above.  NOTE: We currently do not have a way to determine the version of AngularJS within the UI of the rendered webapp... This is also a tracked issue, so your example would need to be compatible with the current version of Angular.

**Comment by gitsome** [comment]
3) So both of these items that you talked about are open issues. I haven't put any thought into changing angular versions so feel free to dig in.  WE generate the head of the document dynamically so it would be a matter of adding references to another angular version PLUS possibly dynamically grabbing the source from the AngularJS servers and putting them into a lib folder if that particular version hasn't already been pulled in...  I think there should be a better way to include modules more automatically, rather than having to add them. That would be a HUGE win!

I could see some type of flag that could be on a group or section that would also inject them in the head automatically... that could be a fun one... feel free to dive in. This approach would be a new issue I think.

Thanks!
